spring:
  application:
    name: svc-clientes
  data:
    mongodb:
      uri: mongodb://cli_adm:cli_adm@127.0.0.1:27017/
      database: db_cli
      authentication-database: cli_adm
      username: cli_adm
      password: cli_adm

server:
  port: 8091
  servlet:
    context-path: /svc-clientes

management:
  server:
    port: 9091
  context-path: /actuator
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}

# custom path for swagger-ui
springdoc:
  swagger-ui:
    path: /swaggerui.html
    operationsSorter: alpha
    tagsSorter: alpha
  # custom path for api docs
  api-docs:
    path: /api-docs

logging:
  pattern:
    default: '{"Timestamp": "%d{yyyy-MM-dd HH:mm:ss.SSS}", "LogType": "%-5p", "AppName": "${spring.application.name}", "TraceId": "%X{traceId:--}", "SpanId": "%X{spanId:--}", "TraceFlags": "%X{trace_flags:--}", "PID": "${PID}", "Thread": "%thread", "Message": %m}%n'
    console: ${logging.pattern.default}